# Generated by Django 2.2 on 2021-09-02 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawlmodel', '0003_snatchermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealhubmodel',
            name='service',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, null=True, verbose_name='服务能力'),
        ),
        migrations.AlterField(
            model_name='fixmodel',
            name='service',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, null=True, verbose_name='服务能力'),
        ),
        migrations.AlterField(
            model_name='jjshousemodel',
            name='service',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, null=True, verbose_name='服务能力'),
        ),
        migrations.AlterField(
            model_name='kikuumodel',
            name='service',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, null=True, verbose_name='服务能力'),
        ),
        migrations.AlterField(
            model_name='kilimallmodel',
            name='service',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, null=True, verbose_name='服务能力'),
        ),
        migrations.AlterField(
            model_name='lovelywholesalemodel',
            name='service',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, null=True, verbose_name='服务能力'),
        ),
        migrations.AlterField(
            model_name='snatchermodel',
            name='service',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, null=True, verbose_name='服务能力'),
        ),
        migrations.AlterField(
            model_name='valuecomodel',
            name='service',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, null=True, verbose_name='服务能力'),
        ),
        migrations.AlterField(
            model_name='wholesale7model',
            name='service',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, null=True, verbose_name='服务能力'),
        ),
    ]
